name: Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.10.5

    - name: Terraform Init
      run: terraform init
      working-directory: aws-terraform-deployment/src

    - name: Terraform Plan
      run: terraform plan
      working-directory: aws-terraform-deployment/src

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve
      working-directory: aws-terraform-deployment/src